### ISSUE TITLE
Godot Android Library 3.5.3

### ISSUE THREAD

**Issue by zawawimanja** [Poing-Studios/godot-admob-plugin#104]
### Godot version

3.5.3.

### Plugin version

1.3.4

### System information

Windows 10

### Issue description

Ads not display when running 3.5.3 godot. For android library ,since there is not library for 3.5.3 I am using 3.5.2

Ads display when using 3.5.2 and android library is 3.5.2.

### Steps to reproduce

1. Open apk
2. No ads. only initiliazed is true.

**Comment by gumaciel** [comment]
@zawawimanja please check again, yesterday i create a new version for 3.5.3
