### ISSUE TITLE
IDFA explainer popup on iOS

### ISSUE THREAD

**Issue by PickleJesus123** [Poing-Studios/godot-admob-plugin#106]
### Godot version

4.1

### Plugin version

3.0.0

### System information

iOS

### Phone information, if applicable

iOS

### Issue description

In order to submit apps to Apple App Store, we must show the [UMP IDFA explainer](https://support.google.com/admob/answer/10115027) window on non-European devices. I have no problem getting UMP to show the GDPR/AppTrackingTransparency popups when I'm testing Europe devices, but I can't seem to get the IDFA explainer to show on non-Europe devices. It seems that the UMP sdk has built-in functionality for this, so I'm not sure if it's just a bug with the plugin

I am getting consent_status=NOT_REQUIRED, and UserMessagingPlatform.consent_information.get_is_consent_form_available() seems to returning "false"

### Steps to reproduce

1. UMP seems to be mostly working properly, and is showing the regular GDRP popup on Android and iOS
2. It won't show the IDFA explainer popup on iOS

**Comment by PickleJesus123** [comment]
Actually, I managed to get this working. Here are the steps I took:
- On the Admob website/dashboard, make sure you have created separate 'projects' for the Android version of your app and the Apple/iOS version of your app. I was using my 'Android version' Gad Application Identifier, when it should have been my 'Apple/iOS' Gad Application Identifier
- [Follow all the steps here](https://developers.google.com/admob/ios/privacy/idfa) (Inlcuding AppTrackingTransparency framework in XCode, and adding NSUserTrackingUsageDescription to your info.plist in XCode)
- (Not sure if this is necessary) In XCode, make sure your project is being signed correctly in Signing&Capabilities

**Comment by gumaciel** [comment]
@PickleJesus123 thank you so much for this information, I will update the documentation

**Comment by PickleJesus123** [comment]
> @PickleJesus123 thank you so much for this information, I will update the documentation

No problem! Seems like your Admob plugin is becoming super popular!
