### ISSUE TITLE
Download of android component via tools does not work

### ISSUE THREAD

**Issue by philippludwig** [Poing-Studios/godot-admob-plugin#115]
### Godot version

4.1.3

### Plugin version

3.0.2

### Phone information

n/a

### Issue description

The installation states:

```
Install the Android Build Template by navigating to Project > Install Android Build Template.
```

However, this does not download anything. From the logs:

```
Downloading https://github.com/Poing-Studios/godot-admob-android/releases/download/v3.0.2/poing-godot-admob-android-v4.1.3.zip
Download percent: 0%
Download completed, you can check the downloaded file at: res://addons/admob/downloads/
```

But the `downloads` folder is empty, sadly.

### Steps to reproduce

1. Try to Install the Android Build Template by navigating to Project > Install Android Build Template.

**Comment by gumaciel** [comment]
@philippludwig does this bug still happen?

**Comment by gumaciel** [comment]
Closing this issue since seems to be solved on my PC, and lack of response.

If this issue still happens please re-open, thanks!
