### ISSUE TITLE
 Error opening file ''. when exporting apk failed

### ISSUE THREAD

**Issue by Pr1nce3** [Poing-Studios/godot-admob-plugin#118]
### Godot version

4.1.2

### Plugin version

Version: v3.0.3

### System information

windows 11

### Phone information, if applicable

android

### Issue description

when i try to export apk i it failed to export and output error i get is 

>  Error opening file ''.
Exporting Poing AdMob '.cfg' file
0 param: --xr_mode_regular
1 param: --use_immersive
  editor/export/editor_export_platform.h:178 - Export: Building of Android project failed, check output for the error. Alternatively visit docs.godotengine.org for Android build documentation.

### Steps to reproduce

1. install plugin to your project and enable it
2. when exporting for android enable plugin and set use gradle build
3. gets this error

### Additional context

![Screenshot 2023-12-09 192532](https://github.com/Poing-Studios/godot-admob-plugin/assets/135206941/167a6b18-fb4d-4ef9-b243-b6dc5a7e66e2)

**Comment by gumaciel** [comment]
Hi it seems to not be related to the plugin, try to export the game without the plugin "Ad Mob" enabled

**Comment by Pr1nce3** [comment]
> Hi it seems to not be related to the plugin, try to export the game without the plugin "Ad Mob" enabled

everything before was working fine it started after admob. but anyway i managed to make it work. you are are its not related to plugin it just godot being godot.

**Comment by mShaffuan** [comment]
@Pr1nce3 can you share how you make it work? I face same problem.
