### ISSUE TITLE
A way to know which version of this plugin I need for which version of Godot

### ISSUE THREAD

**Issue by davekaa** [Poing-Studios/godot-admob-plugin#119]
### Is your feature request related to a problem? If so, please describe.

Although Godot 4.2 is stable at the moment, I'm still using Godot 3.5 for an ongoing project. I'm trying to figure out which version of this plugin I need to match the version of Godot I'm using, but apparently this isn't documented.

### What feature or improvement would you like to see?

Document up to which version of Godot a release is working.

### Additional context

I could be doing something wrong, I'm also pretty new to this so I have no idea what is possible.

**Comment by gumaciel** [comment]
Hi, do you mean this?


https://github.com/Poing-Studios/godot-admob-plugin/discussions/88

**Comment by gumaciel** [comment]
The v1 is for Godot 3, V2 is for Godot 4, and v3 is for Godot 4.1+

**Comment by gumaciel** [comment]
Hi @davekaa does this satisfy your question?

**Comment by davekaa** [comment]
Sorry for the late response. Yeah, that image is helpful!

Since I didn't get it working in the meantime, I started upgrading my project to Godot 4.2. Now I have another problem, since the latest version of your plugin doesn't seem to support Godot 4.2, is that right? This thread is probably not the right place to discuss it, but just wanted to ask.

**Comment by gumaciel** [comment]
The plugin supports Godot 4.2, please read this: https://github.com/Poing-Studios/godot-admob-android/issues/211

Closing the issue since seems to be resolved
