### ISSUE TITLE
Banner isn't at the bottom of the screen on iPhone 12 Pro

### ISSUE THREAD

**Issue by novalis** [Poing-Studios/godot-admob-plugin#66]
### Godot version

3.5.1

### Plugin version

v2.1.1

### Phone information

iPhone 12 Pro, ios 16

### Issue description

![screenshot-iPhone 12 Pro-16 0](https://user-images.githubusercontent.com/77003/207130312-80990a00-f183-487f-8776-109633113550.png)

The banner isn't at the bottom of the screen -- instead, it has crept up to cover my content.

### Steps to reproduce

This seems to be true whether or not I have respect_safe_area turned on.

**Comment by gumaciel** [comment]
Seems to be working normally on Godot 3, i will generate some version of the plugins this days, but this bug really happened on Godot 4 and it's already be fixing

Without Respect Safe Area:

![Captura de Tela 2023-03-03 às 23 33 38](https://user-images.githubusercontent.com/20030153/222871384-3e32d8ce-e319-4629-a2cb-29b7fac7b2a0.png)
![Captura de Tela 2023-03-03 às 23 33 51](https://user-images.githubusercontent.com/20030153/222871394-33667f53-1c28-44b8-927f-83eb64a1b68d.png)


With Respect Safe Area:
![Captura de Tela 2023-03-03 às 23 34 08](https://user-images.githubusercontent.com/20030153/222871410-3ed39d14-4ec2-4c6f-ae18-2d27b04d0e6e.png)


Tested on :
Godot: 3.5.1-stable
Godot AdMob Editor: godot3-v1.3.3
Godot AdMob iOS: v2.1.2

**Comment by novalis** [comment]
I was using BOTTOM for position, not TOP.

**Comment by gumaciel** [comment]
@novalis this is actually working for me, it still happens to you on the latest version?

**Comment by novalis** [comment]
I'm sorry, but unfortunately, I don't know.  I was testing using BrowserStack, since getting Godot working with the simulator on a M1 Mac is pretty annoying.  But I gave up my BrowserStack account.  I'm no longer working on the app in question, or any app that uses ads (for now).  For what it's worth, the fix for me was:

```
diff --git a/plugin/admob/src/formats/Banner.mm b/plugin/admob/src/formats/Banner.mm
index 75e2a64..9f8cee1 100755
--- a/plugin/admob/src/formats/Banner.mm
+++ b/plugin/admob/src/formats/Banner.mm
@@ -150,6 +150,7 @@ - (void)addBannerViewToView {
                                         attribute:NSLayoutAttributeBottom
                                         multiplier:1
                                         constant:0]];
+       bannerView.center = CGPointMake(rootController.view.center.x, rootController.view.frame.size.height-CGSizeFromGADAdSize(GADAdSizeBanner).height/2);
````

**Comment by gumaciel** [comment]
Closing due stale, on #82 it should only appear the BannerAds in the SafeArea
