### ISSUE TITLE
referencing button "pressed" is wrong in Godot 4 and can prevent ad loading

### ISSUE THREAD

**Issue by djrain** [Poing-Studios/godot-admob-plugin#83]
### Godot version

4.0.3

### Plugin version

Godot 4 v1.0.0

### System information

macOS ventura

### Phone information, if applicable

N/A

### Issue description

Tried using plugin in Godot 4, and I wasn't able to load any banner ads, then found this oddity in the admob settings. Notice how "show_instantly" is set to the pressed signal, when it should be a boolean.

<img width="627" alt="Screenshot 2023-06-06 at 5 01 02 PM" src="https://github.com/Poing-Studios/godot-admob-plugin/assets/33777501/6d26d7d2-b2b1-4fcb-a2ce-40e18e87e89b">

This is because of this line in BannerAdFormat.gd. In Godot 4, the button `pressed` variable was renamed to `button_pressed` and `pressed` is now the signal.

```
func _on_BannerShowInstantly_pressed():
	AdMobEditor.AdMobSettings.config.banner.show_instantly = $BannerShowInstantly.pressed
```

it should be this instead:

```
func _on_BannerShowInstantly_pressed():
	AdMobEditor.AdMobSettings.config.banner.show_instantly = $BannerShowInstantly.button_pressed
```

This same thing needs to be changed in a few other places. After fixing it, I got working banners again.

### Steps to reproduce

press the show instantly button, and plugin settings will be wrong

**Comment by gumaciel** [comment]
Thank you, currently I'm working on #82 so I can't work on this now, but it is good to know you solved it by changing the "pressed" to "button_pressed"

**Comment by gumaciel** [comment]
@djrain This should be fixed on: https://github.com/Poing-Studios/godot-admob-plugin/releases/tag/v2.0.0

Please test it

**Comment by gumaciel** [comment]
Closing because it seems to be solved
