### ISSUE TITLE
Editing Interstitial iOS ID is not saved

### ISSUE THREAD

**Issue by LazyDridri** [Poing-Studios/godot-admob-plugin#85]
### Godot version

4.0.2

### Plugin version

1.0.0

### System information

Windows

### Issue description

When using your plugin (amazing by the way), I changed the standard ID for Interstitial for iOS.
It appeared that when I finished to edit it and quit godot, it was not saved when I came back

As you can see on my VIM software, standard is removed and get empty
![image](https://github.com/Poing-Studios/godot-admob-plugin/assets/118674185/92495491-c324-4ec2-9276-da3e9038b896)

I found a workaround. I update UNITY IDS with my value. Then i add a second one with dummy values. And I remove second one directly

### Steps to reproduce

1. Open AdMob plugin on godot
2. Go to interstitial
3. Go to iOS
4. Update standard value (in ca-app-***) by clicking edit and ok
5. Close godot and reopen
6. The value is not saved

**Comment by gumaciel** [comment]
thank you for opening this issue, we will investigate this

**Comment by gumaciel** [comment]
@LazyDridri This should be fixed on: https://github.com/Poing-Studios/godot-admob-plugin/releases/tag/v2.0.0

Please test it

**Comment by hnugz** [comment]
Is that the preferred release that will work with Godot 4.X?

**Comment by gumaciel** [comment]
Hi @hnugz we just released https://github.com/Poing-Studios/godot-admob-plugin/releases/tag/v3.0.0

This will work for v4.1+, if you want to work on Godot versions below v4.1, e.g.: 4.0.2, so you must use https://github.com/Poing-Studios/godot-admob-plugin/releases/tag/v2.0.0

**Comment by gumaciel** [comment]
Closing because it seems to be solved
