### ISSUE TITLE
The Admob plugin does not appear on Godot tab selector

### ISSUE THREAD

**Issue by Vilkinjukka** [Poing-Studios/godot-admob-plugin#91]
### Godot version

4.1.1

### Plugin version

3.0.0

### System information

Windows 11

### Issue description

After installing the Admob editor plugin from the AssetLib or Github, the Admob tab does not appear on the tab selector. Even if the plugin is enabled in the project settings.

![Plugin](https://github.com/Poing-Studios/godot-admob-plugin/assets/45997665/ce0c42e3-0447-4e46-ae6c-0deec7bb83f9)

![TabSelector](https://github.com/Poing-Studios/godot-admob-plugin/assets/45997665/1833643b-a37e-4425-8c48-a3b40a4a1ab5)

The plugin also does not show up on the export settings.
![ExportSettings](https://github.com/Poing-Studios/godot-admob-plugin/assets/45997665/9bbdf9c8-d8b8-4c64-b0ce-48bda0c3d150)

I have tried manually downloading the android admob plugin and moving it to the android/plugin folder, but this does not resolve the issue.

I also tried creating an empty project on my macbook air m2, and the same issue presists.

Is this a bug or am I doing something wrong?

### Steps to reproduce

1. Create an empty godot 4.1.1 project.
2. Install Admob plugin from the AssetLib or from github
3. Enable the plugin in the project settings

**Comment by gumaciel** [comment]
Hi @Vilkinjukka In this release, we've removed the UI from Godot, unlike previous versions. Now, all configurations and interactions need to be done programmatically. We believe this approach simplifies code understanding, as it exposes all ad settings clearly.
